### PR TITLE
Setup for 1.0 release

### PR DESCRIPTION
**Pull request by athal7**
- stop specifying ruby version
- be more lenient about solidus version dependency
- fix specs

### CODE REVIEW

**Comment by magnusvk** [comment]
I think we should remove and `.gitignore` the `.ruby-version` file. It's not like 2.1.7 is the only Ruby version we support, right?

**Comment by athal7** [comment]
@magnusvk good idea, updated. @jordan-brough updated with the solidus dependencies we chatted about

**Comment by jordan-brough** [comment]
cool :+1: nitpick: your commit message says "be more lenient about solidus version dependency". it's actually less lenient now right?

**Comment by athal7** [comment]
good point, will update

**Pull request merged**
